### ISSUE TITLE
A message may be run twice.

### ISSUE THREAD

**Issue by mjaghouri** [CrispOSS/abs-api-parent#23]
We have observed that messages may be run multiple times, and the reason seems to be due to the implementation of `ContextInbox::post` (linked [here](https://github.com/CrispOSS/abs-api-parent/blob/master/abs-api/src/main/java/abs/api/ContextInbox.java#L87)), partly copied below:

 ```
 public <V> Future<V> post(Envelope envelope, Object receiver) {
    // queue the message to receiver
    ObjectInbox inbox = inbox(receiver);
    inbox.post(envelope, receiver);
    executeObjectInbox(inbox);
```

1- Right after `inbox.post` is executed, the sweeper thread may start running the method (apparently, the message is not removed from the queue yet). This happens obviously in another thread.
2- The current thread may proceed and `executeObjectInbox` which then unconditionally may start running the message at the head of the queue.

Example: The code below (sometimes!) produces the above situation. 
PS: This example seems to have a flawed usage of `await` but that is independent of this bug.

```
package auctiondemo;

import static abs.api.Functional.println;

import java.util.concurrent.Executors;
import java.util.function.Supplier;

import abs.api.Configuration;
import abs.api.Context;

public class TestABS
implements abs.api.Actor {
	private static final long serialVersionUID = 1L;


	public TestABS(String[] args)
			throws Exception {
		Context context = Configuration.newConfiguration()
//		    .disableThreadManagement()
		    .withExecutorService(Executors.newFixedThreadPool(4096))
		    .buildContext();
		context.newActor(toString(), this);
		this.run();
	}
	

	private void busyWait() {
		Long y = 0l;
		for (Long x=0l; x < 10000000l; x++) {
			y += x;
		}
	}

	private int x = 1;
	
	public void m() {
		println("1-Init m(): "+x);
		busyWait();
		println("2-Init m(): "+x);
		x = 0;
		println("3-Init m(): "+x);
		Supplier<Boolean> condition = () -> {return x == 1;};
        await(this, condition);
        while(true) {
			println("Sleeping m(): "+x);
			busyWait();
		}
	}

	public void run() {
		Runnable mRunnable = () -> m(); 
		send(this, mRunnable);
		println("Init run(): "+x);
		Supplier<Boolean> condition = () -> {return x == 0;};
        await(this, condition);
		x = 1;
		while(true) {
			println("Sleeping run(): "+x);
			busyWait();
		}
	}
	
	public static void main(String[] args)
			throws Exception {
		new TestABS(args);
	}
}
```

**Comment by nobeh** [comment]
Thanks for creating the issue.

First to clarify that by "twice" or more generally more than *exactly* once, we mean that the above example would print the same lines more than once:

```
Init run(): 1
Sleeping run(): 1
1-Init m(): 1
1-Init m(): 1
2-Init m(): 1
3-Init m(): 0
Sleeping m(): 0
2-Init m(): 0
Sleeping run(): 0
3-Init m(): 0
Sleeping m(): 0
Sleeping m(): 0
Sleeping m(): 0
.
.
.
```

**Comment by nobeh** [comment]
A bit of background on why this happens and why it actually could be also a JVM bug.

* A message is delivered (posted to an inbox) on thread `Td`.
* Sweeper thread `Ts` is busy sweeping all actor queues for execution.
* There's a chance that `Td` and `Ts` access the same queue and run the same message.

A few points on the bug:

* [`ContextInbox`#L127][1] shows that the invocation of `executeInbox` is *synchronized* on method level; [JLS section][3]. It is expected that any number of threads can be involved and JVM will protect the execution. This bug arises based on this assumption on JVM.
* [`ContextInbox`#L91][2] shows the invocation of `executeInbox` in the same thread `Td`. The motivation for this was for situations in which the number of actors might be very high in the context. As such, it might take a while for the sweeper to reach the next round for the message that is being delivered. 

I think based on the motivation and seemingly the wrong expectation from JVM spec, it's better to drop the invocation of `executeInbox` at delivery layer at L91. Though, this might lead to degraded performances in certain situations esp. if the number of actors in a context is high.

[1]: https://github.com/CrispOSS/abs-api-parent/blob/master/abs-api/src/main/java/abs/api/ContextInbox.java#L127
[2]: https://github.com/CrispOSS/abs-api-parent/blob/master/abs-api/src/main/java/abs/api/ContextInbox.java#L91
[3]: https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.4.3.6

**Comment by mjaghouri** [comment]
Hi Behrooz,

Thanks for your response.

I want to briefly react to your comments here, but a face to face
discussion is probably unavoidable.

There executeInbox method only submits to the executor service, so making
it synchronized has no effect on the actual execution of the message
handler by the executor service.

Another point is, since 'post'ing a message involves calling executeInbox,
it seems that the sweeper thread is effectively unneeded.

On a more general level, Frank and Vlad and I had some discussions, and we
strongly believe that abs API implementation can and should be simplified
(possibly by Vlad). Nonetheless, doing so without your input is pointless.

By the way, my availability as of beginning April will be quite limited.

Best regards
Mahdi

**Comment by nobeh** [comment]
v0.8.10 includes a suggested fix and test case for this.
